name: AdvancedReport
main: Seeker\AdvancedReport\Main
author: Seeker
version: 1.0.0
api: [3.13.0, 3.12.1, 3.11.7]
commands:
  report:
    description: "Report players - AdvancedReport by Seeker"
    usage: "/report <player> <reason>"